-- Limpar tabela existente
TRUNCATE TABLE seats;

-- Inserir assentos do Bloco Esquerdo (E)
INSERT INTO seats (seatId, status, observation) VALUES
('E1-1', 'good', 'Assento em bom estado'),
('E1-2', 'good', 'Assento em bom estado'),
('E1-3', 'good', 'Assento em bom estado'),
('E2-1', 'good', 'Assento em bom estado'),
('E2-2', 'good', 'Assento em bom estado'),
('E2-3', 'good', 'Assento em bom estado'),
('E3-1', 'good', 'Assento em bom estado'),
('E3-2', 'good', 'Assento em bom estado'),
('E3-3', 'good', 'Assento em bom estado'),
('E4-1', 'good', 'Assento em bom estado'),
('E4-2', 'good', 'Assento em bom estado'),
('E4-3', 'good', 'Assento em bom estado'),
('E5-1', 'good', 'Assento em bom estado'),
('E5-2', 'good', 'Assento em bom estado'),
('E5-3', 'good', 'Assento em bom estado'),
('E6-1', 'good', 'Assento em bom estado'),
('E6-2', 'good', 'Assento em bom estado'),
('E6-3', 'good', 'Assento em bom estado'),
('E7-1', 'good', 'Assento em bom estado'),
('E7-2', 'good', 'Assento em bom estado'),
('E7-3', 'good', 'Assento em bom estado'),
('E8-1', 'good', 'Assento em bom estado'),
('E8-2', 'good', 'Assento em bom estado'),
('E8-3', 'good', 'Assento em bom estado'),
('E9-1', 'good', 'Assento em bom estado'),
('E9-2', 'good', 'Assento em bom estado'),
('E9-3', 'good', 'Assento em bom estado');

-- Inserir assentos do Bloco Meio (M)
INSERT INTO seats (seatId, status, observation) VALUES
('M1-1', 'good', 'Assento em bom estado'),
('M1-2', 'good', 'Assento em bom estado'),
('M1-3', 'good', 'Assento em bom estado'),
('M1-4', 'good', 'Assento em bom estado'),
('M1-5', 'good', 'Assento em bom estado'),
('M1-6', 'good', 'Assento em bom estado'),
('M2-1', 'good', 'Assento em bom estado'),
('M2-2', 'good', 'Assento em bom estado'),
('M2-3', 'good', 'Assento em bom estado'),
('M2-4', 'good', 'Assento em bom estado'),
('M2-5', 'good', 'Assento em bom estado'),
('M2-6', 'good', 'Assento em bom estado'),
('M3-1', 'good', 'Assento em bom estado'),
('M3-2', 'good', 'Assento em bom estado'),
('M3-3', 'good', 'Assento em bom estado'),
('M3-4', 'good', 'Assento em bom estado'),
('M3-5', 'good', 'Assento em bom estado'),
('M3-6', 'good', 'Assento em bom estado'),
('M4-1', 'good', 'Assento em bom estado'),
('M4-2', 'good', 'Assento em bom estado'),
('M4-3', 'good', 'Assento em bom estado'),
('M4-4', 'good', 'Assento em bom estado'),
('M4-5', 'good', 'Assento em bom estado'),
('M4-6', 'good', 'Assento em bom estado'),
('M5-1', 'good', 'Assento em bom estado'),
('M5-2', 'good', 'Assento em bom estado'),
('M5-3', 'good', 'Assento em bom estado'),
('M5-4', 'good', 'Assento em bom estado'),
('M5-5', 'good', 'Assento em bom estado'),
('M5-6', 'good', 'Assento em bom estado'),
('M6-1', 'good', 'Assento em bom estado'),
('M6-2', 'good', 'Assento em bom estado'),
('M6-3', 'good', 'Assento em bom estado'),
('M6-4', 'good', 'Assento em bom estado'),
('M6-5', 'good', 'Assento em bom estado'),
('M6-6', 'good', 'Assento em bom estado'),
('M7-1', 'good', 'Assento em bom estado'),
('M7-2', 'good', 'Assento em bom estado'),
('M7-3', 'good', 'Assento em bom estado'),
('M7-4', 'good', 'Assento em bom estado'),
('M7-5', 'good', 'Assento em bom estado'),
('M7-6', 'good', 'Assento em bom estado'),
('M8-1', 'good', 'Assento em bom estado'),
('M8-2', 'good', 'Assento em bom estado'),
('M8-3', 'good', 'Assento em bom estado'),
('M8-4', 'good', 'Assento em bom estado'),
('M8-5', 'good', 'Assento em bom estado'),
('M8-6', 'good', 'Assento em bom estado'),
('M9-1', 'good', 'Assento em bom estado'),
('M9-2', 'good', 'Assento em bom estado'),
('M9-3', 'good', 'Assento em bom estado'),
('M9-4', 'good', 'Assento em bom estado'),
('M9-5', 'good', 'Assento em bom estado'),
('M9-6', 'good', 'Assento em bom estado'),
('M10-1', 'good', 'Assento em bom estado'),
('M10-2', 'good', 'Assento em bom estado'),
('M10-3', 'good', 'Assento em bom estado'),
('M10-4', 'good', 'Assento em bom estado'),
('M10-5', 'good', 'Assento em bom estado'),
('M10-6', 'good', 'Assento em bom estado'),
('M11-1', 'good', 'Assento em bom estado'),
('M11-2', 'good', 'Assento em bom estado'),
('M11-3', 'good', 'Assento em bom estado'),
('M11-4', 'good', 'Assento em bom estado'),
('M11-5', 'good', 'Assento em bom estado'),
('M11-6', 'good', 'Assento em bom estado');

-- Inserir assentos do Bloco Direita (D)
INSERT INTO seats (seatId, status, observation) VALUES
('D1-1', 'good', 'Assento em bom estado'),
('D1-2', 'good', 'Assento em bom estado'),
('D1-3', 'good', 'Assento em bom estado'),
('D2-1', 'good', 'Assento em bom estado'),
('D2-2', 'good', 'Assento em bom estado'),
('D2-3', 'good', 'Assento em bom estado'),
('D3-1', 'good', 'Assento em bom estado'),
('D3-2', 'good', 'Assento em bom estado'),
('D3-3', 'good', 'Assento em bom estado'),
('D4-1', 'good', 'Assento em bom estado'),
('D4-2', 'good', 'Assento em bom estado'),
('D4-3', 'good', 'Assento em bom estado'),
('D5-1', 'good', 'Assento em bom estado'),
('D5-2', 'good', 'Assento em bom estado'),
('D5-3', 'good', 'Assento em bom estado'),
('D6-1', 'good', 'Assento em bom estado'),
('D6-2', 'good', 'Assento em bom estado'),
('D6-3', 'good', 'Assento em bom estado'),
('D7-1', 'good', 'Assento em bom estado'),
('D7-2', 'good', 'Assento em bom estado'),
('D7-3', 'good', 'Assento em bom estado'),
('D8-1', 'good', 'Assento em bom estado'),
('D8-2', 'good', 'Assento em bom estado'),
('D8-3', 'good', 'Assento em bom estado'),
('D9-1', 'good', 'Assento em bom estado'),
('D9-2', 'good', 'Assento em bom estado'),
('D9-3', 'good', 'Assento em bom estado');

-- Inserir assentos da Sala B (B)
INSERT INTO seats (seatId, status, observation) VALUES
('B1-1', 'good', 'Assento em bom estado'),
('B1-2', 'good', 'Assento em bom estado'),
('B1-3', 'good', 'Assento em bom estado'),
('B2-1', 'good', 'Assento em bom estado'),
('B2-2', 'good', 'Assento em bom estado'),
('B2-3', 'good', 'Assento em bom estado'),
('B3-1', 'good', 'Assento em bom estado'),
('B3-2', 'good', 'Assento em bom estado'),
('B3-3', 'good', 'Assento em bom estado'),
('B4-1', 'good', 'Assento em bom estado'),
('B4-2', 'good', 'Assento em bom estado'),
('B4-3', 'good', 'Assento em bom estado');
