name: Auto Git Commands

on:
  # Ativa o workflow quando houver alterações em qualquer arquivo
  push:
    paths:
      - '**'
  # Permite executar manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  auto-git:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Git Add
        run: git add .
        
      - name: Git Commit
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto commit: $(date +'%Y-%m-%d %H:%M:%S')"
          fi
          
      - name: Git Push
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
